# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: solar-system
#   name: solar-system
#   namespace: _{_NAMESPACE_}_
# spec:
#   ports:
#   - port: 3000
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     app: solar-system 
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: _{_NAMESPACE_}_
spec:
  type: ClusterIP   # <-- Changed from NodePort
  ports:
    - port: 80          # Ingress will route to this port
      targetPort: 3000  # Your app listens on port 3000
      protocol: TCP
  selector:
    app: solar-system