on:
  #workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ${{ matrix.operating_system }}
    services:                                  # service continer
      mongo-db:
        image: siddharth67/mongo-db:non-prod   #non-prod mongo db use for testing
        ports:
          - 27017:27017
    env:
         MONGO_URI: 'mongodb://localhost:27017/superData'
         MONGO_USERNAME: non-prod-user
         MONGO_PASSWORD: non-prod-password
    strategy:
      matrix:
        nodejs_version: [20]
        operating_system: [ubuntu-latest]
        # exclude:
        #   - nodejs_version: 18
        #     operating_system: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node.js ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}


      - name: Custom Action - Cache & Install NPM Packages
        uses: ./.github/custom-actions/npm-action
        with:
          path-of-folder: node_modules

      - name: Run tests
        run: npm test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.nodejs_version }}-Mocha-Test-Result
          path: test-results.xml


  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    container:                         # Job Container
      image: node:18
    services:                          # Service Container
      mongo:
        image: siddharth67/mongo-db:non-prod
        options: --name mongo
    env:
      MONGO_URI: 'mongodb://mongo:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Custom Action - Cache & Install NPM Packages
        uses: ./.github/custom-actions/npm-action
        with:
          path-of-folder: node_modules

      - name: Run coverage
        run: npm run coverage
        continue-on-error: true

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

  docker-build-test:
        name: Containerization
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4


          - name: Log in to Docker Hub
            uses: docker/login-action@v2.2.0
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build Docker Image for Testing
            uses: docker/build-push-action@v5
            with:
              context: .
              load: true
              push: false
              tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          - name: Run Container and Test `/live` Endpoint
            run: |
              docker run --rm --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

              echo "Verifying /live endpoint"
              wget -q -O - http://127.0.0.1:3000/live | grep live
  
  docker-push-image:
          needs: docker-build-test
          runs-on: ubuntu-latest      
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
      
  dev-deploy:
      needs: docker-push-image
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Install KinD
          run: |
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind

        - name: Create KinD Cluster with port 80 exposed
          run: |
            cat <<EOF > kind-config.yaml
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane
                extraPortMappings:
                  - containerPort: 80
                    hostPort: 80
                    protocol: TCP
            EOF

            kind create cluster --config kind-config.yaml

        - name: Confirm Kubernetes is running
          run: |
            kubectl get nodes
            kubectl cluster-info

        - name: Install Ingress NGINX Controller
          run: |
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/kind/deploy.yaml
            kubectl wait --namespace ingress-nginx \
              --for=condition=Ready pod \
              --selector=app.kubernetes.io/component=controller \
              --timeout=120s

        - name: Replace tokens in manifests
          uses: cschleiden/replace-tokens@v1
          continue-on-error: true
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: kubernetes/development/*.yaml
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: 127.0.0.1

        - name: Verify replaced manifests
          run: cat kubernetes/development/*.yaml

        - name: Create MongoDB Secret
          run: |
              kubectl create namespace ${{ vars.NAMESPACE }}
              kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
                --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
                --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -

        - name: Deploy to Dev k8s cluster
          run: |
                kubectl apply -f kubernetes/development 

        - name: Wait for Deployment to become ready
          run: |
            kubectl -n ${{ vars.NAMESPACE }} rollout status deployment/solar-system --timeout=150s

        - name: Test deployed app via Ingress
          run: |
            echo "Testing /live endpoint via Ingress"
            curl --retry 5 --retry-delay 3 \
              -H "Host: solar-system-${{ vars.NAMESPACE }}.127.0.0.1.nip.io" \
              http://localhost/live

        - name: Dump Kubernetes resources on failure
          if: failure()
          run: |
            kubectl -n ${{ vars.NAMESPACE }} get all
            kubectl -n ${{ vars.NAMESPACE }} describe pods
            kubectl -n ${{ vars.NAMESPACE }} logs deployment/solar-system
