name: CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: ${{ runner.os }}-Unit Testing Result
            path: test-results.xml

    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      container:
        image: node:18
      services:
        mongo:
          image: siddharth67/mongo-db:non-prod
          options: --name mongo
      env:
        MONGO_URI: 'mongodb://mongo:27017/superData'
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password


      steps:
        - name: Checkout repository
          uses: actions/checkout@v4


        - name: Cache NPM dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}


        - name: Install dependencies
          run: npm install


        - name: Run coverage
          run: npm run coverage
          continue-on-error: true


        - name: Archive test results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Code Coverage Result
            path: test-results.xml
    
    docker:      
        name: Containerization
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4


          - name: Log in to Docker Hub
            uses: docker/login-action@v2.2.0
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build Docker Image for Testing
            uses: docker/build-push-action@v5
            with:
              context: .
              load: true
              push: false
              tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}


          - name: Run Container and Test `/live` Endpoint
            run: |
              docker run --rm --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}


              echo "Verifying /live endpoint"
              wget -q -O - http://127.0.0.1:3000/live | grep live
          

          - name: Docker Build and Push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}